version: '2.1'
services:
    mongo:
        image: mongo:4.2.0-bionic
        restart: always
        volumes:
            - ./data/mongo:/data/db
        ports:
            - '27017:27017'

    client:
        image: 925731155295.dkr.ecr.ap-southeast-1.amazonaws.com/pollice-app:latest
        restart: always
        ports:
            - '8080:80'

    server:
        image: 925731155295.dkr.ecr.ap-southeast-1.amazonaws.com/pollice-api:latest
        restart: always
        depends_on:
            - mongo
        environment:
            - NODE_ENV=$NODE_ENV
            - CLIENT_URL=$CLIENT_URL
            - SERVER_URL=$SERVER_URL
            - CLIENT_ID=$CLIENT_ID
            - MONGODB_URL=mongodb://mongo:27017/pollice
            - WAIT_HOSTS=mongo:27017
        ports:
            - '3000:3000'